version: '3'
services:
  node1:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production    
    networks:
      - balancer

  node2:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production     
    networks:
      - balancer

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/infrastructure/ssl:/etc/nginx/ssl
    ports:
      - "90:90"
      - "443:443"
    networks:
      - balancer

networks:
  balancer:
