version: '3'
services:
  node1:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - 8080   
    networks:
      - balancer

  node2:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - 8080    
    networks:
      - balancer

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - balancer

networks:
  balancer:
